# Generated by Django 2.2.16 on 2020-12-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201212_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['is_read', '-created']},
        ),
    ]
