# Generated by Django 2.2.16 on 2020-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201113_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
