# Generated by Django 2.2.16 on 2020-11-25 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_follower_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
