# Generated by Django 2.2.16 on 2020-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_follower_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
