# Generated by Django 2.2.16 on 2020-11-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201125_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created']},
        ),
    ]
