# Generated by Django 2.2.16 on 2020-12-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201130_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
