# Generated by Django 2.2.16 on 2020-10-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='_is_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='estimated_time',
            field=models.IntegerField(help_text='Should be in minutes'),
        ),
    ]
