# Generated by Django 2.2.16 on 2020-10-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20201018_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='_is_status',
            new_name='is_free_status',
        ),
    ]
