# Generated by Django 2.2.16 on 2020-10-19 22:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20201019_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='geospatialhub/pdf/'),
        ),
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
