# Generated by Django 2.2.16 on 2020-10-27 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0006_coursechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_taking_course',
            field=models.ManyToManyField(related_name='taken_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
