# Generated by Django 2.2.16 on 2020-10-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20201027_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users_taking_course',
            new_name='enrolled_for',
        ),
    ]
