# Generated by Django 2.2.16 on 2020-11-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_auto_20201102_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechat',
            options={'ordering': ['-created']},
        ),
    ]
