# Generated by Django 2.2.16 on 2020-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='', max_length=50),
        ),
    ]
